version: '3.9'

services:

    web:
        image: jitsi/web:${JITSI_IMAGE_VERSION:-stable-7648-4}
        env_file: .env
        volumes:
            - ${CONFIG}/web:/config:Z
            - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
            - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
        ports:
            - target: 80
              published: 80
              protocol: tcp
              mode: host
            - target: 443
              published: 443
              protocol: tcp
              mode: host
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    pids: 100

    prosody:
        image: jitsi/prosody:${JITSI_IMAGE_VERSION:-stable-7648-4}
        restart: ${RESTART_POLICY:-unless-stopped}
        expose:
            - '${XMPP_PORT:-5222}'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody/config:/config:Z
            - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
        env_file: .env
        networks:
            jitsi_meet:
                aliases:
                    - ${XMPP_SERVER:-xmpp.meet.jitsi}
        deploy:
            placement:
                constraints:
                    - "node.role==manager"


    # Focus component
    jicofo:
        image: nvantu/jicofo:drl-loadbalancing
        env_file: .env
        volumes:
            - ${CONFIG}/jicofo:/config:Z
        networks:
            jitsi_meet:
        deploy:
            placement:
                constraints:
                    - "node.role==manager"
            resources:
                limits:
                    pids: 1024

    # Video bridge
    jvb:
        image: nvantu/jvb:drl-loadbalancing
        env_file: .env
        ports:
            - target: 10000
              published: 10000
              protocol: udp
              mode: host
            - target: 4443
              published: 4443
              protocol: tcp
              mode: host
            - target: 4096
              published: 4096
              protocol: udp
              mode: host
            - target: 8080
              published: 8080
              protocol: tcp
              mode: host
        networks:
            jitsi_meet:
        deploy:
            # we need exactly one jvb for each host
            mode: global
            endpoint_mode: dnsrr
            placement:
                constraints:
                    - "node.role == worker"
            resources:
                limits:
                    pids: 1024

networks:
    jitsi_meet:
        ipam:
            driver: default
            config:
                - subnet: ${JITSI_MEET_SUBNET}
