#!/usr/bin/with-contenv bash

# in dev mode, we run manually using intellij
if [ "$VMEETING_MODE" == "development" ]; then
    sleep infinity
else
    export JAVA_SYS_PROPS="-Dnet.java.sip.communicator.SC_HOME_DIR_LOCATION=/ -Dnet.java.sip.communicator.SC_HOME_DIR_NAME=config -Djava.util.logging.config.file=/config/logging.properties -Dconfig.file=/config/jvb.conf"
    DAEMON=/usr/share/jitsi-videobridge/jvb.sh
    exec s6-setuidgid jvb /bin/bash -c "exec $DAEMON"
fi
